### ISSUE TITLE
Update calcCovarianceBasic

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/ApproxManifoldProducts.jl#150]
https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/blob/1169d4c64908e712e6d584f09d33572e440153a3/src/CommonUtils.jl#L63-L76

Manifolds.jl now has a cov function that this can be updated to use: `cov(M, ptsArr; basis, kwargs... )`

We should also consider changing the name to reflect the fact that it is a variance and not a covariance. We can then also use the manifolds var function.

**Comment by dehann** [comment]
I just ran into this again, going to add this to the v0.6.1 planning.

**Comment by Affie** [comment]
See 

https://github.com/JuliaRobotics/IncrementalInference.jl/blob/d8c82570bdf7ae0c092f391f66deeff4fd9fab1b/src/VariableStatistics.jl#L13-L19

**Comment by dehann** [comment]
quick work to close this:
- https://github.com/JuliaRobotics/ApproxManifoldProducts.jl/pull/220

**Comment by dehann** [comment]
Ongoing tech debt is IIF.nullhypo code should spread on each dimension specifically, not just reduced to one number as these legacy function.  We can open this as a separate ongoing issue, and close this one faster.

Also see:
- `calcStandardDev`
