### ISSUE TITLE
Integrate with Manifolds.jl

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/ApproxManifoldProducts.jl#32]
Also see JuliaRobotics/RoME.jl#244

**Comment by dehann** [comment]
xref JuliaManifolds/Manopt.jl#24

**Comment by dehann** [comment]
https://discourse.julialang.org/t/understanding-macros-a-macro-to-decorate-a-type/12204

**Comment by dehann** [comment]
xref #41

**Comment by dehann** [comment]
okay, finally starting to move on this with #51

**Comment by dehann** [comment]
Right, so definitions have been moved to Manifolds.jl and future work on building ManifoldKernelDensities will be tracked in #41

**Comment by dehann** [comment]
PS, many more changes happening downstream in IncrementalInference.jl v0.22 and beyond, as well as in RoME.jl

**Comment by mateuszbaran** [comment]
That's great, let me know if you need some help with `Manifolds.jl` :slightly_smiling_face: .
